"""Load data for the competition"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_load_data.ipynb.

# %% auto 0
__all__ = ['path']

# %% ../nbs/01_load_data.ipynb 3
from fastcore.all import *
from oztools.kgl import *
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# %% ../nbs/01_load_data.ipynb 4
path = setup_comp(
    'equity-post-HCT-survival-predictions',
    'git+https://github.com/ozpau/kaggle_hct_survival.git'
)
Path.BASE_PATH = path
path.ls()
