"""Simple tree baseline"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_tree_baseline.ipynb.

# %% auto 0
__all__ = ['path']

# %% ../nbs/01_tree_baseline.ipynb 4
from fastcore.all import *
from oztools.kgl import *
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeRegressor
from dtreeviz.trees import *
from fastai.tabular.all import *
from fastbook import *
import warnings

# %% ../nbs/01_tree_baseline.ipynb 5
path = setup_comp(
    'equity-post-HCT-survival-predictions',
    'git+https://github.com/ozpau/kaggle_hct_survival.git'
)
Path.BASE_PATH = path
path.ls()
